Repository 0x20F/paris, pull requests merged in 2020-03, with the labels that each got.

#15 Icons as keys
  Cargo.toml
  README.md
  src/formatter/ansi.rs
  src/formatter/color.rs
  src/formatter/concerns/mod.rs
  src/formatter/icons.rs
  src/formatter/mod.rs
  src/formatter/style.rs
  src/icons.rs
  src/lib.rs
Labels: documentation, done, enhancement, refactor

#19 Custom solution for key finding
  Cargo.toml
  benches/formatting.rs
  src/formatter/concerns/key_list.rs
  src/formatter/concerns/mod.rs
  src/formatter/mod.rs
  src/lib.rs
Labels: done, in review

#21 Chrono as optional dependency
  .github/workflows/rust.yml
  Cargo.toml
  README.md
  src/lib.rs
  src/timestamp/mod.rs
  tests/logger_integration.rs
Labels: in review

#25 Macros
  .github/workflows/rust.yml
  Cargo.toml
  README.md
  src/formatter/concerns/key_list.rs
  src/lib.rs
  src/macros/mod.rs
  src/output/mod.rs
  tests/logger_integration.rs
Labels: in review
